# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monitor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'monitor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmonitor.proto\x12\x10\x62\x66tsmart.monitor\"\x97\x01\n\x0eMetricsRequest\x12\x12\n\nthroughput\x18\x01 \x03(\x05\x12\x0f\n\x07latency\x18\x02 \x03(\x05\x12\x10\n\x08requests\x18\x03 \x03(\x05\x12\x15\n\rrequests_size\x18\x04 \x03(\x05\x12\x11\n\tBatchSize\x18\x05 \x03(\x05\x12\x14\n\x0c\x42\x61tchTimeout\x18\x06 \x03(\x05\x12\x0e\n\x06Leader\x18\x07 \x03(\x05\":\n\x0fMetricsResponse\x12\x11\n\tBatchSize\x18\x01 \x01(\x05\x12\x14\n\x0c\x42\x61tchTimeout\x18\x02 \x01(\x05\"\x1e\n\tTimestamp\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x32\xa9\x01\n\x0eMetricsService\x12R\n\x0bSendMetrics\x12 .bftsmart.monitor.MetricsRequest\x1a!.bftsmart.monitor.MetricsResponse\x12\x43\n\x07\x43onnect\x12\x1b.bftsmart.monitor.Timestamp\x1a\x1b.bftsmart.monitor.TimestampB\x19\n\x15\x62\x66tsmart.monitor.grpcP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monitor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025bftsmart.monitor.grpcP\001'
  _globals['_METRICSREQUEST']._serialized_start=36
  _globals['_METRICSREQUEST']._serialized_end=187
  _globals['_METRICSRESPONSE']._serialized_start=189
  _globals['_METRICSRESPONSE']._serialized_end=247
  _globals['_TIMESTAMP']._serialized_start=249
  _globals['_TIMESTAMP']._serialized_end=279
  _globals['_METRICSSERVICE']._serialized_start=282
  _globals['_METRICSSERVICE']._serialized_end=451
# @@protoc_insertion_point(module_scope)
